### ISSUE TITLE
Container crashing

### ISSUE THREAD

**Issue by Demigodrick** [Xyphyn/photon#10]
Hey, decided to host this at beta.lemmy.zip, but I'm seeing quite a few errors from people using it via a desktop (mobile browsing seems to be OK as far as I can tell).

The error that crashes the container is:

```
FetchError: invalid json response body at https://lemmy.zip/api/v3/post/list?limit=20&page=1&sort=Active&type_=Local reason: Unexpected token '<', "<html>
<h"... is not valid JSON
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}
/app/node_modules/node-fetch/lib/index.js:273
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at https://lemmy.zip/api/v3/site? reason: Unexpected token '<', "<html>
<h"... is not valid JSON
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}
```

There are no other log files and I can't pinpoint exactly what causes the issue, but it appears to happen on page load after getting a "500" error.

**Comment by Xyphyn** [comment]
this is one of the most annoying issues with how sveltekit handles errors. Instead of throwing up a 500, just crash the entire server! great idea!

This issue is because lemmy.zip is having some errors in the api, and the server decides to completely die instead of showing an error page.

This will happen on initial page load because that's when the server makes the request. I'll attempt to fix this soon, maybe if someone has some knowledge of how to fix this on SvelteKit.

**Comment by Xyphyn** [comment]
welp looks like the fix was to add an `await` so it would be caught by the error handler :/

**Comment by Xyphyn** [comment]
The issue was that the rate limits caused an HTML page to appear, which caused an error in the json parser which wasn't handled properly, so it crashes the server instead of showing a 500.
